# Generated by Django 4.0.3 on 2022-05-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100, null=True, verbose_name='Họ tên')),
                ('ngay_sinh', models.DateField(null=True, verbose_name='Ngày sinh')),
                ('so_dien_thoai', models.CharField(max_length=13, null=True, verbose_name='Số điện thoại')),
                ('dia_chi', models.CharField(max_length=1000, null=True, verbose_name='Địa chỉ')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Email')),
                ('chuc_vu', models.CharField(choices=[('nhân viên', 'nhân viên'), ('thủ kho', 'thủ kho'), ('chủ nhà sách', 'chủ nhà sách'), ('khách hàng', 'khách hàng')], max_length=100, null=True, verbose_name='Chức vụ')),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Thành viên',
            },
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ten_sach', models.CharField(max_length=100, null=True)),
                ('ngay_nhap', models.DateField(null=True)),
                ('so_luong', models.PositiveIntegerField(null=True)),
                ('the_loai', models.CharField(max_length=100, null=True)),
                ('tac_gia', models.CharField(max_length=100, null=True)),
                ('don_gia', models.FloatField(null=True)),
                ('gia_ban', models.FloatField(null=True)),
                ('nha_xuat_ban', models.CharField(max_length=100, null=True)),
                ('nam_xuat_ban', models.PositiveIntegerField(null=True)),
                ('nguoi_nhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.person')),
            ],
            options={
                'verbose_name_plural': 'Sách',
                'unique_together': {('id', 'ngay_nhap')},
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id_HD', models.CharField(default='HD_', max_length=100, primary_key=True, serialize=False, verbose_name='Mã hóa đơn')),
                ('ngay_lap_HD', models.DateTimeField(null=True)),
                ('tong_tien', models.FloatField(null=True)),
                ('phuong_thuc_thanh_toan', models.CharField(choices=[('Thẻ ngân hàng', 'Thẻ ngân hàng'), ('Tiền mặt', 'Tiền mặt')], max_length=100, verbose_name='Phương thức thanh toán')),
                ('da_tra', models.FloatField()),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='khach_hang', to='book.person', verbose_name='Khách hàng')),
                ('nguoi_lap_HD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nhan_vien', to='book.person', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name_plural': 'Hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(null=True)),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.hoadon', verbose_name='Hóa đơn')),
                ('sach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.sach', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Chi tiết hóa đơn',
            },
        ),
    ]
