# Generated by Django 4.0.3 on 2022-05-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='da_tra',
            field=models.FloatField(null=True),
        ),
    ]
