# Generated by Django 4.0.3 on 2022-05-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_person_user_alter_chitiethoadon_so_luong'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='anh_bia',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to=''),
        ),
    ]
