# Generated by Django 4.0.3 on 2022-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_sach_anh_bia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='anh_bia',
            field=models.ImageField(blank=True, default='static/placeholder.png', null=True, upload_to=''),
        ),
    ]
