# Generated by Django 4.0.3 on 2022-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_sach_anh_sach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='don_gia',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
