# Generated by Django 4.0.3 on 2022-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_sach_anh_bia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='don_gia',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sach',
            name='gia_ban',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
