# Generated by Django 4.0.3 on 2022-05-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_sach_don_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitiethoadon',
            name='so_luong',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
