# Generated by Django 4.0.3 on 2022-05-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_sach_don_gia_alter_sach_gia_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
