# Generated by Django 4.0.3 on 2022-05-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_chitiethoadon_so_luong'),
        ('book', '0009_alter_sach_mo_ta'),
    ]

    operations = [
    ]
