# Generated by Django 4.0.3 on 2022-05-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_merge_20220526_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sach',
            name='anh_bia',
        ),
        migrations.AlterField(
            model_name='sach',
            name='anh_sach',
            field=models.ImageField(blank=True, default='static/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sach',
            name='don_gia',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
