# Generated by Django 4.0.3 on 2022-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='da_tra',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='tong_tien',
            field=models.FloatField(default=0, null=True),
        ),
    ]
