# Generated by Django 3.1.8 on 2022-06-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20220609_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='ngay_nhap',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
